version: '3'
services: 
    postgres:
        image: postgres:latest
        environment: 
            - POSTGRES_PASSWORD=admin123
    redis:
        image: redis:latest
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /app/node_modules
            - ./server:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PG_USER=postgres
            - PG_HOST=postgres
            - PG_DATABASE=postgres
            - PG_PASSWORD=admin123
            - PG_PORT=5432
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules # not override
            - ./client:/app
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /app/node_modules
            - ./worker:/app
    nginx:
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        restart: always
